# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: The Dataviz Card Game
  fr: The Dataviz Card Game
email: your-email@domain.com
description:
  en: The Dataviz Card Game projects intends to create physical game cards as a support of knowledge transfer on the theme of data visualization. The Dataviz Card Game has been prototyped by Cédric Lombion in 2014, and has since become a project under the banner of Ecole des données. The work on the project has been partially financed by School of Data's innovation fund.
  fr: A TRADUIRE. The Dataviz Card Game projects intends to create physical game cards as a support of knowledge transfer on the theme of data visualization. The Dataviz Card Game has been prototyped by Cédric Lombion in 2014, and has since become a project under the banner of Ecole des données. The work on the project has been partially financed by School of Data's innovation fund.
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "/dataviz-card-game" # the subpath of your site, e.g. /blog
url: "http://ecoledesdonnees.github.io/dataviz-card-game/" # the base hostname & protocol for your site
twitter_username: ecoledesdonnees
github_username:  ecoledesdonnees

# Build settings
markdown: kramdown

#translations
t:
  en:
    langLabel: "English"
    readMore: "Read more"
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about.html"
    contact:
      name: "Contact"
      url: "/contact.html"
  fr:
    langLabel: "Français"
    readMore: "Lire l'article"
    home:
      name: "Accueil"
      url: "/accueil.html"
    about:
      name: "À propos"
      url: "/a-propos.html"
    contact:
      name: "Contact"
      url: "/contact-fr.html"

# allow array variable
array: []